### ISSUE TITLE
export laws sans `Arbitrary`

### ISSUE THREAD

**Issue by matthewleon** [purescript-contrib/purescript-quickcheck-laws#35]
It should be possible to support quickchecking laws without making use of `Arbitrary`. Here is an example for `Semigroup`:

```purescript
checkSemigroupGen
  ∷ ∀ eff s
  . Semigroup s
  ⇒ Eq s
  ⇒ Gen s
  → QC eff Unit
checkSemigroupGen gen = do

  log "Checking 'Associativity' law for Semigroup"
  quickCheck' 1000 $ associativity <$> gen <*> gen <*> gen

  where

  associativity ∷ s → s → s → Boolean
  associativity x y z = ((x <> y) <> z) == (x <> (y <> z))
```

**Comment by garyb** [comment]
👍 

I've also been meaning to export some of the actual properties as standalone functions (like `associativity`)

**Comment by matthewleon** [comment]
> I've also been meaning to export some of the actual properties as standalone functions also (like associativity)

I believe there are some PRs around, at least on the Prelude, to do precisely this.

**Comment by garyb** [comment]
That's true! They've been there for so long I forgot 😬

**Comment by hdgarrood** [comment]
Yeah so I started on this with https://github.com/purescript/purescript-prelude/pull/111, and I was starting to think that returning a `{ lhs :: a, rhs :: a }` might be better; see https://github.com/purescript/purescript-prelude/pull/111#issuecomment-275951753

**Comment by hdgarrood** [comment]
Ah, but that's separate really, isn't it? ok never mind then.
