### ISSUE TITLE
Add DivisionRing law checks

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/purescript-quickcheck-laws#37]
See https://pursuit.purescript.org/packages/purescript-prelude/3.2.0/docs/Data.DivisionRing#t:DivisionRing

**Comment by hdgarrood** [comment]
Was this fixed by https://github.com/garyb/purescript-quickcheck-laws/pull/42/commits/88b66b58daaf17dcc6d6444ae3946e5817e17c87?

**Comment by garyb** [comment]
I guess so! Assuming the checks look good to you?

**Comment by hdgarrood** [comment]
Yep :) I've left a couple of comments on the commit but they're just minor suggestions.

**Comment by garyb** [comment]
Thanks, I'll leave them for now but will keep them in mind next time I do an update here. I'm pretty sure there'll be a few other cases like `nonZero` that only need testing once!
