### ISSUE TITLE
Publish to Bower

### ISSUE THREAD

**Issue by Fresheyeball** [purescript-contrib/purescript-quickcheck-laws#4]
![Please....](http://www.troll.me/images/please-cat/please-cat.jpeg)

**Comment by garyb** [comment]
It's published now, I've not made any releases yet though as this probably doesn't work with the latest quickcheck - it's intended for the version we release with purescript 0.7.

**Comment by hdgarrood** [comment]
I would really like to see this library published - is there anything I can do to help? What needs to be done?

**Comment by garyb** [comment]
I have a version I've been working on that simplifies a whole bunch of stuff. I'll try and finish it up soon and get this thing published at last.

**Comment by garyb** [comment]
Released at last!

**Comment by garyb** [comment]
Now I need to make the same thing for strongcheck I guess...

**Comment by hdgarrood** [comment]
\o/ thank you!

**Comment by Fresheyeball** [comment]
:+1:
